---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-nextcloud
  namespace: argocd
spec:
  encryptedData:
    clientID: AgA9CKb28UBdLwLQlhDjDrogREL1YE/MNuczWl7NyOg409AvFiIIfVoReuwZuxEl5bqImXvuwbpvWOH2KH6igf4YwnyCc64DCgC2mJoD9qeYDYZq++UwsSKL8U+z/0O3InnRDThmGNUJhFoO5JRI2fQe8pD8JMfHSxIFlnZGaaSyspIG8+BJY+xDdy4yHTaFxVMg6hB3ZXheHpYPloa95zXKC4ywJKUDH1PmgQ3hZdV7ac6qrjPDoSQ7Rq8tgJkDzPqFabkzA95BLCt0h0hg+6sFJwFRzGy7dnQ9H9Xwg22BxvgS8Tl2JxSoGw6AkXOby2qFCaDwsGgWVyR/0HUgr2Z/jbZUK3JKM1ALhIQgvdfQmxPrObKSVg4qWZbokF9DTIfsepkIgl1QmXU5HcL5419+gPX89+dUaLDDcwWAEsNTsourAFRpuqEZF3TicQjpKF0aEwTatPCyV96rT7R0OdqOkkojq/kL+ta45DKbEzzroFY5xdTBY9BR1dWHjXjUx8GWp0vp70+Ds7Di1yrNiS1YyKHxJogPIy9p/4YH2InKuzwzDy3pltjSieariXrBkq7k2gcFU8xXtrXIv+PcCvDZuB0ZXlnNSOHmCy8N+nI0VdWuRSTkEcEBd+zQ5E4QIR2mGhCrJeLCXezOe0AiR+K5W4Sn68oYkhwuKvoFrZd6gaNaAb/BegeSm2W28mmUQ1RzbiCKQkFXgx8Ril9Jy83Mvmc+CPtUDO8Qgf0kqYMZhVhhPfKJWVKSWX+pE4XG0KWo1p4+kptlfloUSe5XCZAP
    clientSecret: AgCWR6qgCzMGGbilbSARNbKyXQUb6/NwmxjkkOGBBtOC/YgrSAUZ2ighuJdped0SmozWzFwx1DRVEyuHIlQCKXdoj23RYiKn0PpQ/hx2ljSfXIi1bcAtrD99JwZJnXG3jnxaLNN/K63BojTIrp7WBG5CpsV9iQZ3Vg5HrEAvSuc/1q+XYGe1lC7baMEadzggs1a294JgqRp2xWusycxrO55PVaq0gAzeW1l0VoQOcfKtd/ncOMqdNDdEaePbFWhy7aQU3flCtDzs1POzfFj3ZeZUl0vZ7m9pH8EXs4FBs1qoH2YjGkvejoYp3tB2Du5pIWHXWP62avJxalgwZuNWah6gxaLQygylSOCrkAQ7/2RfMntlc6Qjn0lSO0wBknb3aqdjb99vzqaPLAB3tOQ65AIjQfbh1WCRlKlZS790uZFHsN+n54rtLMyEGh1hnYQG/N11hVGTxU6DG2daRlYY2O50RHrXKFay4o2LCHTMFT0Itfm7Xfj43Uin2nbOD5l6vy5pbi1aeXe4NLJppZRMMyjnoaLagHUkTLWv3geeymw0rwBhEtr4wuveoc/aThyf1S3MgG8OCjnddLkjaJLnLEVsQbWh+3o70980fI0bqTdFVDWYHFCJG/2nei8Ch4hpOkoSidCUbWyBOYpG3TKGKZq4UpdzzpArygdj9REue1KTd7dQV8W5aNbzDZC8MPdTK4DzJYdm9CA8GkPK3lJ+w/6/Uv+9WZ94VE13VZnH1iURvUMOH2tmgndx3mAJ4R/ptSZ5E6rwhKZUoULM5Qa68cse
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-nextcloud
      namespace: argocd
