---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-github
  namespace: argocd
spec:
  encryptedData:
    clientID: AgCpoivpEqUu7izTAfEE9RQHDaaJvTBoHuRJeFWkouHmwaZ1ElYZ9+8dUB11CIcbeA7TjPTpqMWiDYhPDN4659R/JSalf4L73s9VOQViQzco/CFXZjQSwve+RV89/ncs/JDNaycAOX5ZN1qs2dm2vRGh/ZdjLnnXjhtwOR0/Y5+0XFzlXXucO6yPRfbN3EkVdZMGg3TTKoaVRDghJGwACOuB21AruDIwcUtLwxyTxMLgWcnmEAJNlxiiZOBTShYq9sjbFJi7NFVT9ujpje6H66abiqjCfishRV7HevfMMTbIwuJe/44AO8AKO5E4Pv8wQDZ24xBOD0z0ezgzOw8MPykrm9PB4ci19zb3z8MWvknn0wwnGP4TjBsniWetRgMXOboVZwJqcbrBq3JAemcOmDB7qA+P1ZFNSNtpfNd1oF6aT6+2/FnFJkDVGAQRixX2TV7sVq0IuE7dMpbcitNMwZJVESYAoMIOS8GlgVJjlLYu4iPc7IJxO4dpeVv7CDCyIOzCiu0a81xHge0uyKRSaat0ImGmdKmeXUaQmNHuGnTQsF9pum4SpiTszVbDLXF1uuZeDU6Izz4acXytz6HXOsWzPOzF5XfP3tjY574P94bLlyyRAJF/gisrcdzgW5mDlhqzfh0kJCCo6+U2VaTpwdXZuu19IK/WnUNfJQNS3giirHj8RwSqAzTG4XF56KlpHnGhWDbf6lA6z4FiU5wiEWNxxD1aGQ==
    clientSecret: AgBVSpFERwAXYNzXyb/ZBJVeQg3gwkDI8+rBBpW806pucvmITxqUoVRrfELcCFBc0rAPEB+Kq2NPGiZBncpMLkHD+89pKiBPtNGSgfV5xC9JXJJMTLLOHOBDtcK0yAw+eCPhSy6s/HBm/kFM4P8D+VCSMoMNedEc+ssieWHmy4AeBSjflhmE+ZxN1H6QOojz5lOta/yf8f8gSN8sDbB9KMyR37bGd1DeCzgC5ezRuity9Fr6N6X1TSUVEDHCG7OTZBqeEdM+0PFBZQhQragyZxsL2fGQMLr5Rw7Lb2/NgsivG8U0FURR8m7ddmBclri9ilhSsn7njqvVsESMTI/tGvjd7ghjVYJeVL/DA8IRk/GzsXaEs4E2MmoYK3vAkJX5Vg042+cWVhiiMmQ8XWzeGnDENeWt2hbt8dKdexEet8xGAVuNgg08pSTbC+t8/mmNBvVShDEyAwyHE3jXmSr0nzqDGKhiWA7iWR9dCxVvOrvJjnB7tFdvWZyAuy2Na75jelvW2SP8etXOb3YWMN42g666Z8Pb4aSVA9FsGldDOTsehQCTfCP6HkCNJGMFEQ+Ti7Uz86nzCb3f9rL3hXMC3TOCQChOiEh0i7yjDc0yfmyzZqjzs8Nd5r9d/BsvLWQLm5gDqsCPjA0G2LRvWhkqV1gjhpa+bSLSNUU/fO8KTBR5ecY0NL3GHMdZTlAob1/Yzx27+SK9LzqrDtx0oVij5v+7AnFanlO5QBaA16A13f3dSnSJS8wKaDQh
  template:
    metadata:
      name: argocd-dex-github
      namespace: argocd
