---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-github
  namespace: argocd
spec:
  encryptedData:
    clientID: AgAGHKZOwt+BP6WLo7GPqxV2trvzwrrcr25UZX7s8ev22HaADjk6EF37QS5M//OATZ8q7ylnRBAohb0D/aR+tZgeHariwI+xp3Aj0Oco/YvR72xatDaedkT3QLCFu1pigQo212HujHCmm8nX85Y8/VFA8k35PSUAovdWi7K/UPZlWVed1sC5W2nNjzR8lq+LvSv258FXfa+aWaUCtP3cmhYggWeMvICxgqv6Q248/oNhHq5W7wKIcY6LOdkeGo+J05FjHP54LHuM8LrhI7JC8W8p7xUJCc23dUd0UsTt1xNZ8iNZ1OsYJbUZ+a2mXRhGsuCCTVzd44gHZr7CJwbu5RJqhx1GeWvlsFTiLmJwkq9caNqlcg6AcqNq1YJAIo1GYpPTcZfD6+a5WZEgFINNqd41i9woPjYq8jp07qJo+CSd5SiMcpnfWQgBldjKq0qsjMJYaQUHLWRUUEhFmT+BfSdHBRTlfLZb/ru8SD1wJB8u9KSdQGIOHHQnfmtLvFjV91CEdby0takHtKzpmL+57XViyC6qZgtVN3duM0GT1E8hB3D4PDE9JPDp0ZRVn8QwiXIEUgTY1XVmr1jnBiYGyk1NBsBxEUnhl8d99ziU/dY2xpX31OT9Y5SEpooupz7JJih3PbPsC20xQlqsRp36Ri8KTiZcrQgx2Fak8xAbtha1DoFXHb+8/p82eZWhdcrsnCe7UcPE1KRpxWQxtGKPrGf2L6S8fA==
    clientSecret: AgAwIxCHRTakVfyE7WE4rUFsPiMjr7QO1Un4OpAnCtnjufMmKXvBplDBaMND7TWR5kWi6EdUEwrRI/L/QSe01vzHtiNsT15dzK6LC52VelWsu5mMX7Uj0Eo8Jv1WC5UecXpoFHfwvB/LsTmsZIxV49mr3a7jw8aDhai5WQLCCloLkVzDX4E2BTndQO/3wfxpFUSCH/gyEQY+YZlxkVFVi/3ShxX5OsjweODV6sFRBEknyQmW0D29hGiXcSO0CA1mavy9IZY5lXRUUre23KuEl8bVU5vXn1diHboIEyuiEUI0QuL8toca2vuclOwTT/rzVLzIPU0gdPPHNgp/ZQJ1HTy2yXFnZGKsR8MNs5S9hn7B/dCqnoM3LCV51pct2al7Y57hgUW4Y4OfHVLqT6utw85A1Ye9DWexsnh9U7rHWpfiWs98hifCa1CKdu7/hNcAOUD2Oqep0GbBXynqD7z3Ewe6YsLQexyer67rHtxgd+HpzapfPvBx5cjqS14X4jTXvjtLzPxbhkHma45IjSrqM/rmCic5ZCDiDHb3AnjXt3AId/0dPKw4jxEeNkdwvKdfWsta/EmkkoEO5EPuPvU08ddzQK101Kg3DX9a1BHaHWDRMjmFIjt7d+94KX397fPRmcBbs37aQ/JP67VRwNYe6ok9qoOlfhTPxrTdSlnhrNWpi/03AKxR7R5U8myE+lxEzdWZqVTMlKSt9sGw+yDLmUYV2eWqgeXpRuUVkkp5Y/CxVF7K33rUs52V
  template:
    metadata:
      name: argocd-dex-github
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
