image:
  repository: ghcr.io/garmeres/garmeres-frontend
  tag: latest

host: garmeres-frontend.balve.garmeres.com
ingressClassName: traefik

strapiUrl: https://strapi.balve.garmeres.com
calendarUrl: https://balve-calendar.hel1.your-objectstorage.com
gaId: G-D4DKCE7RH0
appSecret: garmeres-frontend-secrets

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
