---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garmeres-frontend-secrets
  namespace: garmeres-frontend
spec:
  encryptedData:
    STRAPI_API_TOKEN: AgCnjJ4FePUtK1aTcdepGWA6Z2vIzNdeqj5+Ayb67Z7mUw2VbAmjqOtPC5Y4KNU/0hFHRoQlHPxfXXhheMioU8HVDLKw1QqS2Tw6LvJ4FKUDMwLADXr9GABupd9xH6WTi80xkOVJM5KcbyiD08Rh6sl9FhoCXH/IO4p3QWbibXVQCctL8YM983b5/4kWlBge/YgVKBYiXyrLF+sWgru8zJLSRxGDJWPRbJ2Pdu9KqYov08YJGOUUlBnSUIEm3ekn2RFBwSdfoX/P3EZRreex73Yaxl0QcHlu/WGL7zbldTlYQ4OJ/4l97TvduC2wHl9y3M+23gQ6vFGN5rDXMDSid7B2AMD1YMIFFforCCAsDa4qxfA4OqKCXT8DTqfs/osUM/Z4kkxVVFnglTyZ/2ycalwgwUy0R2e7MLFL75qe5YcRwh+YXkQaZKdwUVqqoL6jSkyIsIXAHP2fAWiauQ689Nt6cafuHoiGvurboNU9g4EtthnCvsNR5ylY6KrEBXniMvf6pcCvGUh3CucLRbiwyz696859lMH9JS+58G1JK/3V4WeJt52woW1OmvuAUxImmPzHKsTwTIhOBWRZaFvqsTYcoBRrsZcAV95ooImWQDgjDWlXm0g4tRMBzYTwsdeY2cTlukkU1+XtyldP1uZ7xb2HwAZqKcEMtub8ElIFrRKi1pqd0FidyvsnIzdZZF3WW9vsIKKszBgdL8WiYwHQUcpdv5JhDPtTxUubLH/J9n7VISr8hza7gBUruKIwYcr7NpAu9SKn2VH1z1tIx/roqE4eBWUlNynNnkQDMl+m9UEfI2UTRc7yfsGY9ZzDUP11z9xoge2EZgYmP2FfRCVr416Ldzlxo90K0D22jgCpHXkkQjIHRSTW5RhQpzHRW5hEm/2LPgD0IL15QL9ig6ffpIufQNfvBdn/mnT3Z34VZNJKl6e97OFcX6XXoPOlSYFQ6ucg1wt1APzcdtqq5seMH269ZpQ+a1OYq3YxjlqWbKLP5KMkdovcc8To6x8iz4cROrPOgIjuTPSywjaNk5tYIgqh
  template:
    metadata:
      name: garmeres-frontend-secrets
      namespace: garmeres-frontend
