image:
  repository: ghcr.io/garmeres/balve-strapi
  tag: latest

host: strapi.balve.garmeres.com
ingressClassName: traefik
frameAncestors: https://balve.garmeres.com

existingSecret: strapi-secrets

s3Secret: strapi-s3

s3:
  endpoint: https://hel1.your-objectstorage.com
  region: "hel1"
  bucket: "balve-strapi"
  cdnUrl: "https://balve-strapi.hel1.your-objectstorage.com"

backupSchedule: "0 23 1-29/2 * *"

resources:
  requests:
    memory: 256Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 500m
