---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dex-github-connector
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    clientID: AgBXlnOGImntP1yjIAvhV+DPu7tRyN20fHTlYHIm/BmHE8F8RAGAETTC4te+1InfaU3yimlb+LRCUo9bCnY7lPg7+erhYbLjw6RBCT1fDIbofQPpJ53JoNhzbXA++7lOS1u/3rNGoDdg9WpxbSO5ZykfE2gSdx1yod+54OjpLSBd3pUWV8ZjZyqWSHzMC7KosQJogZQTHPRJVIb08vQhMwL47AMK8sAThNbqR5MR33sJz//k6wBAudsMLaqK8uTLs7swmzGvWpqoKJOe2yZXzRQwsBVJBRggt9kbEk6vPr8w4S6jHmOTKuIpJvQfyMAIDNjTWX0k7hTCJ1RogATNn2o04LoLTW5H8kRmwBdGKcCrzEGXdpBDaU9+mqGxLZqn6DeHE7NUD+PUoR5/GxjCkQMVhIPaVPXKVzK61VlkyiNZTWjiUdvoA9j6zahQ3WhsyUhfia+fK93qYyIrjG8jyWWFne8cy2hl9MfFE0gzWqFV5yYCi50exjKLktoGer9WOx9466h/0trePdiTP6hy2hsGPBxbBHvvOmD5K2N29DzColvRbgXlm6SAKCb+v0DRhXWX2LGKmB6pMOUMnFIgCF9y9vFAXEGWFs5SNyeDB/+KxrSNv8C4zjZHEexphRsEudkLFfu731ddr9r6Q2ts1TSjSQfSzXlThORTEGEswMULKbAZqpzoYzmOtPR78SLhPkI/CvpJlrFsG/kqX+Z2PqmgfmupVg==
    clientSecret: AgBrc/iKn6+vj9kkAljT1akWVUCcLiKOmJLpxeU4WAZkqPGVYPYAqoJhEzjfFJfS70nQv/il8cbw1En5/z5ifP11pt2XWGfm+ld8mfROZxnYHaJrFInaZ9cnJ6TUIZNAVvU9C5aGaX/g4URf2Pa/SfQCBw9g9PgJdBrsK61v4/ymdVtCNHsfJ//eAd/yj1WVjcrv8FvtNWm/XqUn1sMvG2T4yn57m5l2YvfkD44ComabDEzmkFwihD7lxBba9YLp1LhJlA51MWkddIQreYecDYXm6xk9HGRuYIx1ppiwHRp7QWyVxxInHoM3+eXyEFBCA/bjWYLApV+5/lxzPeaDrJX6CMgxr30p45zk6y7orMlJT8Xx+PJL2N9cNKeOzSZ0NoKzrHabszJDnOBwOniAOrPM8rtioqitBEGEQfdZzs95TvyZJbzq9+Xx33KcUwk8Lum1ocuoyXeUlxhX1Fx3KOVTrEtKcVgXOoJXGj2I6/ClyrSslVevt3PkWbz3Pms77ghVv2Tkv4SoOLx+EWrMCqg2qod7X+ygFQctJR73XGtom4mAaWP+OIQ/d8oTErdk4NJiogjhzjhEzcO4bfVv3ZdtLY0g5gsG3w/UD/bu/5EPkhNLQVHKWXTbfu04PqehY/GXJi6Ncnq7TMT6hYnRopXiD/bfOD+gk3UQS9G7DUl6/jnn4P5wUinAl9aHvo6KjoFEL4kXIJAJV/YiHAMetiM1lqf4E67T6lcghPvLvOH9ZKB8in1hdWl2
  template:
    metadata:
      name: dex-github-connector
      namespace: dex
