calendarLink: "http://nextcloud.nextcloud.svc.cluster.local:8080/remote.php/dav/public-calendars/DG8C8Ys63r3x2qSx?export"
eventsPerPage: 10
schedule: "0 */6 * * *"

targets:
  - name: hetzner
    s3Secret: calendar-sync-s3
    s3:
      endpoint: "https://hel1.your-objectstorage.com"
      region: "hel1"
      bucket: "balve-calendar"

  - name: aws
    s3Secret: calendar-sync-aws-s3
    cloudfrontDistributionId: "E2D0IEYH7SFG25"
    s3:
      # AWS S3 uses the default endpoint
      endpoint: "https://s3.eu-north-1.amazonaws.com"
      region: "eu-north-1"
      bucket: "garmeres-calendar-sync-events-bucket"
