---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: calendar-sync-aws-s3
  namespace: calendar-sync
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgAgZYwByKAfy4qkPFuqa9kj6QfvJ5uZjmUEKnDNTGRCI+48Mr1l/toPkyxH9gKUpiW+QmFDaKh2ZOtf78x3+zO88aORalEQBNXI5iaqonNtMSES1OQEXA3eEvyt3odc7EZbdX8AvI4Rs3hCUSiX8dypmI19OJu923GLRmG3YeXfDRccPpat/KeTt1ATcbTRC/emP+a2XGVGgDiRngRlxO2/csOovMOCKyKH/ASCpDB+G8GfHSpxBcDJMoJCa5Bn8VNDsrq2DyC13MuDwpEWHkb4fiIr0NoyfyQ40VesF2crmqXhXm3iqeYH9ZlhA9M27VD0H2/anbRC7sc4B/P/imCg3WoW6EXAM+gv5OgOIy5qor2MYUBqP9MN9nHd6qiVhgNSttI1/6PUBrD0zEHyhxhMJjB69KUqw/V1zd9ItLO7iVnqUD1N76hEmx/WbwCfILNe6RI4OHxe8ClV/CSfPn9U09diAhmnOgESKZLRyd2zMydxqWgLSjYj2t1pI2yjwJOGf0zdB+PNCrscbHBLIvS7tguCvUWbhq3HWwhA89nd5nCD0duR9UbV1BtABksqUsMQ938mBsLRXMzmmhNdDR5IqMONPsrUR23d/Pc0kUao/GLiI4RVlMRoUVD5Z61AKmakIZvHlj+zeWHjhiFa3kzxmZJPt36X+jQnzLocmOU4vSUM1Nj4ePt1PemuXp+AvkyqBSdXp3eD4jzHRjEAWa08MGBrGw==
    S3_SECRET_ACCESS_KEY: AgBf98gHMlNbG9duUNktAS1nsFryrs8vKi5NwW+U1wq/BsIUDVn6DG2Iyan6FBrn8RwEpDS3vWYUB4sQzFLc6M8iuAuo1B6s2i40i1S9QlwNHzqHIR8FixugwnBLDDa/YH2lfQnn4O6aL18J1xN7jSNFLQBPlG5fjhmPjNBPWCvMQUmfQ11ESZBGQX+uK8Ox+/GfYD9JLOw/91SdH286ESzXJkJyrzas0BIMQeNhiX6kFwC+vY+r59kUh7aPuXOweypTngEV5Y+LOZI2iMqiTIqACGM3SbtEFwMZwT6tyLReOrSttRrF6FefjLFYTmmqlS+XnG5riUyKZtHgd7rnQWqQQihLYiR3i6NyE7fjz/f+u3o3qq+uvPrlhea+ixN4XQWVfg0A529yTpX8j4nb7dqUce1goAyxn6O7fbb1t72MaVPLK6R6PHjhG+G2lmK4QPmE/WDUEiEELCH+LNLTKUPQMSrEJLvQsdj4Wq0DeSw5fjXxVoQaklyyO193EbFM2/46mNqgQ/DUqcBrlIsxFbcPvUGIKdJzf/KiZVYU7gs/9VlozxuJ3ONJ5J4CRt67k75JutUjE/dgKUGxqdFIDVQFXh/4iOaoFf+HDopDxKKtUHd5ip52InQbh6RupcYRIRjc72s4rbEZiA5YhMZdqFUQ7efxiiiwoKEyHdNrGjySbKSvTIvP2kqT8JR8pgxBvFszNEzeMIecfUZ3e6n4OHzuiLSp2KN7YOcx0cFmEmQ668rvdtMaq84V
  template:
    metadata:
      name: calendar-sync-aws-s3
      namespace: calendar-sync
