---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: calendar-sync-s3
  namespace: calendar-sync
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgBRFd+UvsGH/c43eJX6C6ojetzLqZmkzQQVvn+6XIEeaOafInwre+b6vLgekXlbUFbLvgz5Kk5cTLljtWgX8aJh1Ah/24e74nUoU1XJRHzCoxjsFWqAoiXo6dpviyT3VLw8RuDwghyoAsCOCNVXzetaMAwS+YOdFpSNQ568tsXWwgfepFeReLCUSZ4GKFOu7eo1gdb3R+JrtxMeEws0GjyMcBWB4lDZLZ1s42f/OyTfAcko4k4Cor7bDm2gwaDa231FMCPG8qpR2tFewvDXia7nDFx3kV4mNVkVXGjAXKMDcBnHWM0GlNe/jzadeDd2hRjRZVnUTla1YTcJ7/KI29RHbPoItNR10INFD2nLA3QqppHVZAu2hHXd5jm2YbYiqhFIBxc6VmTMOKxls6qL2edOz2NzvJsBdlsNvF1C4XMmK/GB3uT3VdKDy4pB7yZbEQTv8VezHbbB6dklz7qo0XYeqcGGr0OXKfIlD2u6oT/mLXm76dBAEH1c0i73jiXmHG9rVp70cwBGnFicRSTKdzCFEgDaJRZLcX6BlZIiMjh+De9Jphoty9LeqNQLx+mpkMPnoCDVY9yPBTfqLIKJrEa9SvdVOGDwjqa/ciO/IgiNg2OPlQzNN2S/6nka7z7FWT9sSEd8gUUc1cjoWQ7eqU+Gv3y0JpyXSedjwLvRV4ao+XsjsVhzKU5J6eY9VajoaGSU7oLAInIB8S9DYZh/FFweJeOL/w==
    S3_SECRET_ACCESS_KEY: AgCgPSLmArnhZAHqaMBXaB4YcHBxAacV+bugibDPdGnei/+wcFQ7Qxc5E55pVEn5nivnkVxwDkGB3qLMCQTKL1cwf/7AuD4CFLd74HW81e3WUtB7R5Cu2Q8e8k+2VK/0G+cFbaTBD5ed+d9fYVwuyhnIknUAPN5Q1jiMESJ6AcTBLmzA7Dz5Yyx/h2pkmVtlmvA8n29DtUH8F7h7sLSf3Ie0vQtsNMRK9yFxQHH0JR3Dh8dXe8Cw0Yw8krkaukGrBVooCHLhBwoRN/sHxOsIZdEq2Fluvqi6dl2aRlF63upvswk1l0KOmx+838UEeQ4/GmR9otXqKk1O1KDp9eTcPoNPTV54K/g8eJFJlbSVNSVjj5pHzYDrPa2yEV6HrfYptuR+n7lcBJruF9wVHZeAuFmatevSp2r/sRDBj3qcnQ8U6qzWJcbqIhEMiHIgqP3mG/CHyxtGVH8IQkRcRZtrn5g738jNtA4yrBQwMW1/U6kWu27GTDTlcSfpqiHFnnYCGa8aYT8ZJk9eljQgFORxjN5FWxpGxvJm4iARLWcfJEF7DUV1aTlwO/4H4J1uqC4s9bEqbvCVQuNe1jpcOoOsdloi3elYWzTw0h8H6ewjgx97Se/zvy8pvy6+7C6Jl9MUhJ4D7J55ptvIXZy5qmzrHRnVBxFCeUFFZ+00BVNWXGaG2sstBTTDP/0qNdOjmZevzcs0U5+IipOY6HuvleV0kvrE/j5xqTRJtjVvuTG9swkJGh09CFPe9F9T
  template:
    metadata:
      name: calendar-sync-s3
      namespace: calendar-sync
