---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: calendar-sync-aws-s3
  namespace: calendar-sync
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCGxIr4R0+Dn4PcAS+x5aNxhDhXzm5aQZdsPARhG+98XbbNQi6a2uFJ2KvCoN8GGRQoB4uNjKYPJBDFdpDTF7e5ZNSVg9njvR2Rr8PeuFaFrOKv5fGj6kBrNIBb443jg2dw64fKLbLdQBQWBy41nQXvFuHGHg7M+y6WTsmMEg7hPidqMGVJglHU2rQJkgA36AbeD+3TBcb2zb3iWjmQ1B3H6ZVvFQIWvYX5L7dK1GfZq4uQcoXYOdy8wnZAQYlh+tJvlTNqZpuexAn6UlH3KM2RoSfos2dCb+w7JjfrLHdygYp4hSdobLnaywmtpWC8jQMJqO0E9zwBmmSeTrETphTR39dcxWnSoneoZfQkvNbaoJ/Q2UpzH0KUpEe3iXyCj5iCx+7TM/wJcd3tdX80uUBm0a3A8FNk2tr9iEpuCvO1HfiAlKWiI2jvjE+nIxr36YdYJu7CYJIfS/kaidjbGDOKUfJRlR4b1E9klqIowLOWmDth4QVgnEY742V7fg+m7xx7VywB+n5QqRUzCanVxxdi6aLda2LIQEEzhmMfRwgYa5dPq99oPtKKJRg0AwlUV2Wzjh98pL9fDetzckR6VNTz/XsueY6C/ANCyeeqsej3RsOsa/VYVp8qjq3255/406Rqen/2wo0sCn+OVBVTnYeixQzVd2A/NhSo6aKNxCC3RooftvDB8fB2wFNFC2bhWO8Ekh35dmL9/zLmHhCmvsJMs5u+kw==
    S3_SECRET_ACCESS_KEY: AgDA4ncV1X84vBGnl3ag1uYrNnDl3/H07OW5ZdXQDf6Wz08gXuepQysu8dxqOVQAfjU415TE5Np4CTOqt+BG08A+05fYpzJy+nZPfzrYFwzpboBIWbU9aPx7slWW01c/4fWjGybFW7zaKM8TbyimkoSaB/B0XXAWWVPQ/J/YhP1NSa6tI2m2by5mWVKulL3Wd9Ktb8Glmnir19VdQVXtvuKLFcJfIbBpGAn2pfO3ccydhidx+MKW0y5bbIV+613QBxxCJ7oQiFsw4GZeztsNR/1WASP9iKBzxp2i33SPTNNY/DpkHO0NFHmBkLjxhDvz2Z7Yd4snWjJ+PrkQO7XI3AJ1Wa859MlaMEgMGCpJNTvJbNoBowrth4LNT1aIbLfBD/G36IS8V5ALqy10vx/9xhLEIEluqAwqWzlOQrR2g4kb3GeHHm1VnVWUCWy0d1Rb1iUqrz++YA/m83xDKFTpXuUjH64frnVi8JPRPMls7+qQqy5v2tlblj7xfe0MLXbWbvGLv5qQknhi9dWzRQDrw1vV2bSU1SveyHbF9Yo/GSLUCIqxAMxGHIQgdv4edc+/b0H10yhggksVYxA2A43YrVchmcqUtH1tya+fTSJ5ma0XaJrQO4ngQsBGrlsJJ4H20konlAujOTvwig8ysEJuLySxkebOCB3Mq427NWLHltXvKDncFyNxS1W7VvG8HpPSHlPLs+LEP2ZDlpZvHQQu1fagRUZVrj9Qjreg1KFxl4tpMoP1QZRR7Y4k
  template:
    metadata:
      name: calendar-sync-aws-s3
      namespace: calendar-sync
