---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: calendar-sync-s3
  namespace: calendar-sync
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgAOxIlTPE4yU1P/mRNQ3VmhCCYtDhPupCSCv53UT//VqtHmKwW62X/s1aGU0dxz7XASD/6gf9aD+3GyNdPkp+AqapFew4PKrot6c/4Ufh6/18ibQwRJ3kIazkSrSfFRLm/0D2IOYl3T693paW5o11UmafrJVJ1Cjv8EhQW5QeaJFqntlGINZ/umHYPCZ/b43cFx9NA2d7vSsA8ya8qmgQbdOaYcOnWf6HxcAU2ajDW/iCXtmTcAHHy9zd/UnOBg2M8XMzLKrxxr7n5VLfO+LWzE9H9/BBwTuUpAZyjowi2upVGmB9rHjl7jiZkqAL3lXpFiSTRuZcquJunbHiFg4g+UygoX2FxEhe645r0TLYrUuMJ4chpPlFV2TxeLY6/wV1pUdIpoqZts9i88LqnwFB3UrZJzfkV/HKPxf3ywD4d27mEAynhEL490J+NBXfdkri8qXpszbTY/8eLrGndmVai45AWhn9Kt/VkNBLoH0NyJ/UdXOPBH0IR8ZbVO8XLQTGFXaUYHJPooCG3bazl0YKd1V7SDSma51n6lYTiLRFFU+oerGAH56bRt04plMfc7jhak0oP9lTt5kDITSSrpQKYhhuECRgdSEJe/eVMUSjdPFKJ6LV3o8epaA6aapjCJTbLJ+v/UAkk9d2y936OxvmXK4zO2jU7Fx+M4GiGbgioROvIjubp+JMz/lnsDDlqZzdjiMic8xO3cUq8xqZwyvClxa4WZyg==
    S3_SECRET_ACCESS_KEY: AgCadptDYpOIRhYDJLYkgsJZFTDlC1UnW6CqOe8AEF8+j/r+LktJ5y7j48crYDiFQhwqMlsUaghNm/97zFe+FnDzBej8jrsFNusisWQi+tFJM1JT2+4V86kpjg6ne0sWN2IzVx9StnLYrU6wxy55Ebg/t6HoJCayfEsZ9nC8ByJS9Qdjem2HuTPjXa1fYxnyQye5PrUvrY7+aFYKrRsl0SRJHu8y9usWmdymMPaCzi85HSmq12u/j368s76AM5MJ1h2lhMIc+bCknUmAYxvB5yBuGOu7iTq3k2K7O6LamRsY6npzpUXZBCNc7G0tccTy0dDK7J8YEBOqpaqYWAT9aMLqql8Jv3z6x8DazcXOntfDDzMbdnca4OAnzna1bwKoceJwWyvyrSNyZjNAOKcnW0L7c4nZ4oPeHpl4RRvL6mqtXvL9PEcBg0vdVEc/cXA+zpyNVKy37F4sBmMuNEh7QxoSJnAr+zn4FP3lxlff2pwLpyaGgROSFu5CC3hRTEqVLyAnSP3XQaretYLy9Qdy2zVFgpzNAcjIPF9lmYwghQu6dxKFWg9ttQNCfT33zUMJFUPC5gweIlwyNeqZJrHa29LFm/S59pbDfphv7V24B8n+GU4gTXJ2BJSbq92oUgrKeWZ7lDdmkUHQ2aAKMmiYqglyMQcbVYfPKcyTVD84SGfzOjhJ+a6ENNAzTqiGXUUKtg5okLLrwHP1BW6NXXyyxI5XEFyxubI+2JVMZOPP119lY2aXX3SguASH
  template:
    metadata:
      name: calendar-sync-s3
      namespace: calendar-sync
