apiVersion: v2
name: dex
description: Standalone Dex OIDC identity provider
type: application
version: 0.1.0
dependencies:
  - name: dex
    version: 0.24.0
    repository: https://charts.dexidp.io
  - name: secret-mirror
    version: 0.1.0
    repository: file://../../charts/secret-mirror
