apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  generators:
    - git:
        repoURL: {{ .Values.repoURL | required ".repoURL is required." }}
        revision: {{ .Values.targetRevision | default "main" }}
        directories:
          - path: applications/*
  template:
    metadata:
      name: '{{ "{{path.basename}}" }}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL | required ".repoURL is required." }}
        targetRevision: {{ .Values.targetRevision | default "main" }}
        path: '{{ "{{path}}" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{path.basename}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 2m
            factor: 2
            maxDuration: 10m
          limit: 3
        syncOptions:
          - CreateNamespace=true
