apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-nextcloud
  namespace: argocd
spec:
  encryptedData:
    clientID: AgAvQ2f4YYZk1Wk74TgXn5arbqmVAJ6Lhwyi4sD2mG5Aea8WOQfeSavvvqIQFOGQQekEWklf69eQd7hpTi51HJIQ6JrrE2jEsLL7bb6umQL9S9YifO0cxt9v+Bsek/2l9n5PfaCQPxOnOdnK2oFgr5IfYckZbl+29PEPUCAPReauTHEP7KnvDqTTRfqCOlobvHhg+Yli9Dt8VB5ztZDGwn4YMCRaMlG06TIjU4Jo5P16hDsQLlK3feEtakRB/08I/N4sPdnROU1Q2P07jRs0xkgVTuHUaRG9pGok9iHIZ17mMAcTMt+bO0D9KOZMiTwPbIzIA2hEG3j7nuxn3cj1lp7OVBImF7UlPow2mW57LPF/abqJpPNX3ujgRWMYGoR8jWZ5FHKBJ3OSdAphSHANutT7v1tOJLkiQEaoKRibFhMEK7hVzvRFGucds+vnxDtGUMMrzEYWFL9LpBU4zjAOFwD9cSsUCgCq+gXZAua53W5m/bFPjTEe72NebK6yTOH1DFJI3LUWa09qJwe5OC0L90ImY0YpZyARhdWPtL6jUTK920+ZAj12d5KTL8AFKPtWa39pFMpXp4t8o/77T71ilL3xp26NVPNhkPOOfT8ugAKm5aLafMoWVqyxAmXjIyiGSXBbnTJM1HUzus/3BmsSYSWgeFCBKwmSJ22MjValDDLZt0TkEE7L+SY/CFHtnTTP7Oz+pvWTilMV89T4tot+SbIoM2cyizYThpDx0X6mJTVak4RpvHmXNoYZFIWX9OOsmgdUuYLyPEWr0Y79gxPoyRVh
    clientSecret: AgCT19es1yyY5TtpVaXSFIzusGpbIkUg6IRCX7aCeZ0BHL9xdsdp2vHXfUu+wI0KVtNMuw4Ign2CiL7+ivf2Bm0RuovFc/JEitrpdE7Bbh9Savr6QxHGeKHyVJkO7ru+G0OiDX/G9Nzr/LsG6z/T9aNAlANuWSAGYYwbLcdV+infmoexrv6MzF/HD1CrGthdXPVhaLU9pUhGoNy82dF9MCH016DpP2kwWPSXSJHqmdcFVx287K8Q5fQystppLWF9pSJMFkU5et6zAShbdNyIhWpBTK8YoOeSrlNsdjZHZ+8hFEd4EIxiTBdCZoSRXo9+1v3Pke54vC0Ns21iErtr/qgo1JhzVc8wBy8kix52iwN27IDl7fyw8fNOdxS8CyaZ6TKH/++ChQgpUO6DtnMVWu+iTOVP/wli6nYFKeZjsDdadZl9fmkgvNNW545D7L23jkeTSxAwlH+2xgb61aZFkJ9WFjgAnYP+bPzsp6V8+WCdfY0gu0c102ioXOexiMS6kWC6jjijZkBs76E/ZH43TAgATORMZUShfgzCol7MsY7n+KDGbJPRGisvI1xJcz5vpETKlI1Wx4zxdiYq6gnHPOJejx/2UpfZxsYo6eDeMnjADDA9t3JG184+Xkw3fuuAKnRg7Po1fFoPCFwyOVBD0ujDfJoH7S+X2Dv+2RgaKkMmnR6fFI4VonIUF69UpDZJ3WKLLQPomaM0koTFQOUHdaZiN1AmPemq0cuPxkiSfuBkalbB6+alAEGeA3b7u78kGCcmlSLX8Kn/3+qPQn6MeS2V
  template:
    metadata:
      name: argocd-dex-nextcloud
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
