apiVersion: v1
kind: ConfigMap
metadata:
  name: litestream
data:
  litestream.yml: |
    dbs:
      - path: /data/data.db
        replica:
          url: s3://{{ .Values.s3.bucket }}/strapi.db
          endpoint: {{ .Values.s3.endpoint }}
          region: {{ .Values.s3.region }}
          force-path-style: true
