---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: strapi-smtp
  namespace: strapi
spec:
  encryptedData:
    SMTP_PASSWORD: AgBqEFIp/bTrrpq5Xb6DRBdto+FJ6l72DqEAm6vCkJBHI3/SZlBA48n9HtHNWiV1hBXB8kv5ogqyIWXzTUV8hwvvjqjol3MXi4sXJTIh3AQEL/CQ1eOzy/pIk7MgBuScatywlrHs/orC9HKNYG4hnZRIGsOxJQ/iaihuqPGFXOrlQZQZTkjCn4e6lbEcThGMiP1lZpLOR0MZnvmoVvA3b8eDYUatC2yxkT5OYl1Bn6LlqR+1BaepwUztuq87ZGd+8Odpp5c/lOa5szP41bga6AXgRFIOWwrvf+6t8tPYLRxDZzZ/hQ63VOPpYplbHsBBGIb8rtKo1zXiVFViLtN7F9cDYHi77H7936GwjQNkijOeZcPOjI8Y59TJ/Obi2qwtW5lJNSvnu4x+4OW7luIqe9HEP5Oi0mUs8exj9KZm5BUA8kDY3yJTSpAEfJnt8pSYPh0CkM1pAu0v1FL7e5jjQEwOKeiwOVb4AuOC9RNlULzl8xQUO9RqvFrJXSEfVult0uB+4u7VVGvcqQ45l3yD/Aznaxs8HH/PM565A2zWEVjWZzPF5+mPojyLUWqW08+gLm8PFN2jEK1dxWu1hxI9Ce6Sy4jW+8xvPH6s3zxgDI7oZT4UeShnxTyBPvawnyQuDdynHvh/VrBKBD1UUbaCh9S26EdOaMKOMxJ8jRC54bxRklKCAuAWfq/mrP6GdD/ejBJDsWNqoKgZ/XeVbpYsHE8=
    SMTP_USERNAME: AgCYN/oUA2H4Izjf/bcgEjNc/qyQY/JuJ+xq5Z4YlRxAGGJy72Z7m0P/742VASrUEMqVo3n58YeBvl5W+CEiX8eSKVUYuA9oQc6yKHUQEdGKXD4CFtcgOiXskoQMC+s7qxbBTkyBvcxUidoTP4htB00HZurD9nQTTy3EWeLcitz1EOtybiX7vfh1ihlW2HJT5UFAHAnX/Fw9MokBgwoF5QRQoX5h4dhP8R9IKErMWsNpY9QbFVSKRqGhIpE4xiHDgK918b2X5k2e0BLGXLiywRqykjRMEzSp7Eh6CXX+JJLO2JYpUmtM12ZrJrZi3aqkcq8nsNFwncOIKRiIo5RfY7UUMZnjjrBUOc1pp1gHUpUSuXHHvnxVBJC8Pso4bY2P+mkmjxZcAucCJP5canFyM3FcjRCIaix+/uxrrwjdI7ZbuAG+HXMdLk0kj8zCR3kDPr3IC2BRk14sZ+YOiA9MxCrfqUQNflKEXXL4CBVUDB6P9JFLLe6dUQD4Mi9K5oTq2YtH6UqW/y9phuH1RE5ZzyVp9Z3ZuYl5FUqFPuo7kBld2MH2IsUd8hYYH8EE/HB2bEkaQ8UzMJw1LrsybLjWfRhlCKFF/SCFx1CtP1ckbyqxhDJvtRrlr1S9DSNeso0wtjdqMD+PJDJhkRWVXFDzTA5hC9TtGc4sZe+L3e0ViyjoiIAnGD8hvLiXbWAmL7OoO20Nz8WvmWqp3IXM
  template:
    metadata:
      name: strapi-smtp
      namespace: strapi
