---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: strapi-s3
  namespace: strapi
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgB20K5NGK7QBKL2RflndeIk8lHItAd6FQ2Yd826tlUSfyAdvNALjU5A+JPJLE4yS+1bRtDuu+wHm9EuY41uX4htv5636oX2CM/ga6UC0YCLBm348bKDFqcRpK1jkmlSsluErchziXZ1NK1Dj0KVuYh3sp5CI9mLKB2PAPPm5hpSgk4gbPsQCJYHHbBHTY93SCGJf9nNXZGeXbbJCrzLm1nBCVQsg3tlykblEjXgdXZ+FNI6PRPDbpDvd58BxlLVnL/GaQohBKH91oskEjE7dbFT1XoXCQgLQv3Atr4hdbPOB1Fk8CSLjeWouuCcSeFKnf4lgEU5U/5ipMpRqyY1BN8shBs4Du34+nBMvLUZeAbT4xgV8a9ES0ICm8Wq8wsBZabX2OZ/bACn6Bpn81YcKQq8rhyohT9fNtbtKYaZIbuRsHg5FXhMDjuGVeBLMTKbmIV7mba1ofNAl3jzUwF/57eDSDY/1QgdI2y99LSZN6SFoHhe0itTuk4DDhVHmB+XpaU00jJAISqyQWRfY3+PQYIfAXuJiSqNcrsUkbzn/XyfMplyJ7mK2jM010nQpmxlTtQpkAU3jd2MdaKgJYzhzZdRamIZn+An9oqyTROV/R2NXc7LIDP/NFJKJcOW7ucv3JoLAoklYZeocuYhDcAA3nLuzBTnUYyzGuTJzWkdE2T5iXVxYIkb2s+G4dZh89VED/ImL8Iw4lfA90D/nKHv8Ojs8UnELQ==
    S3_SECRET_ACCESS_KEY: AgCOrXTeyGoAZ3lxHoWZNrb3ZK3x+obpNED8qAZZ2Z2tZAVEhibcwX3bqqvHQ98cLneOd9Z/6vteSsqgUPbGKGI7oaRONMIUmS2ns+cxTI7TK9oLHmrT9lGPtSV/+dSFuq04xNzjqwDSc4YFb4Css8ESHkfbPMm3foU4oxOOUWSv5YXPRa2U29HivVX67zeFHkEdGSTAGz5kIP/oYycs1ie3N0cz7Yh6zdKEK/nM1ZymbR3pI+tl5us6XfdseeoY4Wqbf2g4OYgi51elUpuiWjw+in83dnnwIJqA1lm4D4i2iiPqnkl2zUTs6ZyJG3EhgHDqdNNWX2QbSSil7veBDbFcbAsPuN8ao3OQD8Kh27RdPjhQZBnIgkQR99T2Z/0FBhCVItnYDcRNR0H70+tXq5wqSqCNaeqft4OfIMFMfrccV6iQUhPC+XYXeEbsvWCXQnl4aGh9xhdBJzFh6ffPcwOb4nb52bQL+khnLOJH4ndBAOYtevoIyC8PHUk7y8MeihHZA1vOT3/aFtfBNjOJWFcj2K5+FHM8C4X5dgY0G/GrpRh+WgBZgncK40/wI/c5KIVYW8qWonVBOca3RO6S3ufQGnKdDipkFzFivlub3nsiTVCT+Pnm4SDqEdpG8zpzwvO74yHnUmvtdwtHxCtX1PrDbELaY0OHYqHrgXyLp96FXoajM8yY08WoY1yiXxlvzbSvyCWCHIV10iS2bdoMNYUqINofDCgbsNvUxJqJPYYyDKmD5/leEKcZ
  template:
    metadata:
      name: strapi-s3
      namespace: strapi
