---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: strapi-smtp
  namespace: strapi
spec:
  encryptedData:
    SMTP_PASSWORD: AgCD+gTf/8QvwH7Sa46I0AWKQqc+MSfpeUpdkAn+olHmTA1w9PaIlnm4h9ZHp6S/JiyElqxUgkLez9zWaSkLunOjwMckm9ZZ0j1k/v+KNKUmVodwbOvb3UnFplcbeYqzGJDn94O5wGotMwtzYWghRW98YckcezUd8SUy/Z7rPjTY4mjOLEYj/d+gEBjVPQBAdG/9HARz3/vUfhe1x2rFfPTTbWgiD2+fWvHVeuy2s0IC0m6jGGFb9k8p68JYYr1+NB3vEbs862i2VSf2t+M0YX2UDXofmZz8spFeRpSeB/DluE2xdfTn9v5twLcIjnEV3Qvg/UDXAS4WmB+qNrKPsFErdqRdZFV9NfpO9xcArmnYaWUT3Q1YeGtiiqoGoB6dRpE3iCz/rM8ydEXfjGmxLamKFM6Jyg8Uud7RrRwfEVDB5y/v8Hc+yW5a7plPNnkKyi5z1JJ01mFlSv/1iYGaoKaFPz5YDIZVJLkJWa/HSI9jhtZ78lbokhhx5nKklweOHzVImS+7eJkORtYi/l16YYKjcLbJTkN0/zFJUZcKOFDwJwAUsmfONt99qXl/0BQufD8z6b1VTgSVflmnBvhqBvBvoFo0zEo+3ua9qb4hFhqQGzn9sX7EYe5WLyWmi7pdxTgcqxyxmODR3t3FRqr5yl6l7DQSzWRNlz3j2wg8eL8c2hVGY2JrrxnaKhFWboVr5pXoch0LPyTtGD/K0JThA71GLnEm7uiREJiiDXzYepblSQ==
    SMTP_USERNAME: AgCEhJ9ZkhuCDKRrWYz2kEAc1gLgni2wnPAWW3Bf49oV0tDq/Cuk2rBJ+/ReVsg5xFPy507MhvuEdl6FOH4+CfL0FXkkH02Hq64MjQTPlcKSt2mdebVtOeRvQ7fT8qhemRwzGQiFqC05Fo/SSfTGRziAXlAJ4Se68Xe/79SwfPkSWLPZ9qYbFzNfxLgF0O1Yu1Ax+XIPlJ7Cdr8M133rLoz5aclZqKbN4ZfkpbeMeBdPzICBN90Exn1iQelnij83egbnvT2dE+0sDLhLSRQgNsOLS/0QkToryPBLfSCb7h/vBg+fXipABHaa5pygyoucBR0MP6bsInr3tv6MLloGe08I+VJ1kw/Cqw6rdPY9LnFXs1Nb4m56v8rgxOe8IxTmxxbkSqpNvlhKX6Ya3ANaU3JZMWmQ5rtAYVoY2+yi1VH+JJQvWmMbOnYe7ckWEVNVCyPUJHoQSp8gT+d90GGHpxqfmggAdL5c6d7EEOtiZZl+PyKdFihGSaDYWT+Jb7ajG2MnxMJFF0oFGF/bXmJ96rZHczPVPJ6bwhP1rr0u47kQ0U5dLT43BJDGUMvM2MqiBsZIqJX0bzzGy+QTPWMiDI740gEUY9uF+vmjF1HGLiJ7N+UvREHnoPyUlqYU7oF1/xichqYWVwkA/aBnXqroM05jyXuDyFqVvcrTnG5pRUBshH92TqQaK1l2QryOptL1q+tzQck+UgyrT/VD
  template:
    metadata:
      name: strapi-smtp
      namespace: strapi
