---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: strapi-s3
  namespace: strapi
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCSadBqrLXkXEVsdxqn3HwXO90boBGqL3cbW2t8Ni6IGowQtC6MyPW8ItcRYdzizqvJ8Kj/e79xbtKmo3EenmmeGx3xxgLTlnah1l+dcehFlw/mZABSM2E4zW5fjGVyyR6Dwhm1ft3LxKaMI6BSvj5Y8eiit7XvchsNt4yqGjmc9LkOxCIbBK2G48kiMVbKcxMoqqLb2epe2qbcLrACa6lb/cMwJGq8MXTpnropKLuc+We+NDfEgyC3Yc/s02BxCwDfw3B2n8Spj+OInkf2Ewv/Saplgg3WisM+vatj84S215ZmkXQhDcQFsaTou3fK+8865uiHYTbmZmKX9TdhI2P+gEHPe0HSbNPcFuUwN62tGe8urAzkU1nBMjwYw9KxcKCMVVsACjfrr/2LfJH7yMSxGG3piDuOEpfgMymuow7P2k5ooSSgz0ERLnjL9caDcRz3z4Zar+M5f7dFllHdVwH2qNrYZxgdEMyOOD0xXoDHIyv+bt7nZk1GhusYHK5DoKoOZBbFutXsBBtXNBZ+0oNh2dvGgS68ojxJ1j7wJTxXqS9zA1Ew9Wy/XRojt4/PLdlD91O05E3nyev38k8mcucJk4RhPb7CQib7zNjaVzvu3n88ua+bZfddqxd6dC+4FrIHXo7hfSqFKUFxtsftqlId32zTTrQM8hjRjWUJGUQy1cW+9rHeYv6yuelx8eRiEfNmSvd77K8SnSjxZxYDIhS2A07r9Q==
    S3_SECRET_ACCESS_KEY: AgCUCoFODbvczauEwqmqgSDbGHFugt/0mDPWyHvE+caH7Ej4sJ13c530/8IAGY/OZGaDeRmffrJ0LxxWI1y/eYX5SYmgajKEBq6trj85fig2kzgAxWnMnuqLPEGwjG2r7oLbU2w8dJTWGZ+Ci5f9m4sYB0uQm+h7QjwqEDxo38dzTXEcZKKG3hyTDSKI6dlkQgQZNMcP9Lkyt9/FXtMSWeq+2x36aYo2Mi0jEjNvAkxYjV+fkgghHCihLOYKzO/uWjdTDyyHlcUlLjL1tNvvyRPUzTSrb29mZuHnpVeOhaqt9Plfyg5Sgr78yzC8ojcskEUAIFyi812ttDFxTEZJioG6rdn5TSpYKfqpAZSXV3k1cDU7OaDsyW88zqd+qHoT6EOWI6X3aFqj3AILY6Q8v7WfEnFDrW8+Nf/VQj/tS+qAh0nk/R805di4cnnoy8yH2oqxXyRqxoXMT++yfYb7IIV0r6tFCy5lor+uu4nxYEcZGuluCjfPDjFtN+wWZDnBM0w0V4LZY01EdLbvNPbmFukHFdhmzTKIC51dLRZXZJj0UeVhBb4WsmhSCEirpHj/lMjEdn2OKHm2RK//WgtWWQJ587YEMkJbJZd32qbwtyTUI2LT98IteACjXpwh/M0Yv5iv+jVXeQsNVYd6VYGOxIXu2IH09p7cTztz9RXHEaFGV0iPSKdJHckosot+Sf4n5cW8KK8ouE4VE+PM9Xlr9foM98QRjLRC1wUAFj9zJqHvXZ4wy920/oik
  template:
    metadata:
      name: strapi-s3
      namespace: strapi
