apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goatcounter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goatcounter
                port:
                  number: 8080
  tls:
    - secretName: goatcounter-tls
      hosts:
        - {{ .Values.host }}
