apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/garmeres/balve-k8s.git
        revision: main
        directories:
          - path: applications/*
  syncPolicy:
    applicationsSync: create-update
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/garmeres/balve-k8s.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.volumeClaimTemplates[]?.spec
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
          limit: 10
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
