argo-cd:
  global:
    domain: argocd.dev.garmeres.com

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true

  dex:
    enabled: true

  configs:
    cm:
      admin.enabled: "false"
      url: https://argocd.dev.garmeres.com
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: garmeres
              loadAllGroups: true

    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, garmeres:admins, role:admin
        g, garmeres:developers, role:readonly
