argo-cd:
  global:
    domain: argocd.balve.garmeres.com

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.io/middlewares: argocd-argocd-chain@kubernetescrd
      tls: true

  dex:
    enabled: true

  configs:
    cm:
      admin.enabled: "false"
      url: https://argocd.balve.garmeres.com
      ui.theme: auto
      ui.bannercontent: "This dashboard shows the status of all services on the Balve server. Green means everything is running normally."
      ui.bannerposition: top
      ui.bannerpermanent: "true"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $argocd-dex-github:clientID
              clientSecret: $argocd-dex-github:clientSecret
              orgs:
                - name: Garmeres
              loadAllGroups: true
          - type: oidc
            id: nextcloud
            name: Nextcloud
            config:
              issuer: https://balve.garmeres.com
              clientID: $argocd-dex-nextcloud:clientID
              clientSecret: $argocd-dex-nextcloud:clientSecret
              scopes:
                - openid
                - profile
                - email
                - groups
              getUserInfo: true
              insecureEnableGroups: true
              claimMapping:
                groups: nc_groups

    rbac:
      policy.default: role:viewer
      policy.csv: |
        p, role:viewer, applications, get, */*, allow
        p, role:viewer, logs, get, */*, deny
        p, role:viewer, exec, create, */*, deny
        p, role:viewer, repositories, *, *, deny
        p, role:viewer, clusters, *, *, deny
        p, role:viewer, certificates, *, *, deny
        p, role:viewer, accounts, *, *, deny
        p, role:viewer, gpgkeys, *, *, deny
        p, role:viewer, projects, *, *, deny
        p, role:viewer, extensions, invoke, */*, deny
        p, role:developer, applications, get, */*, allow
        p, role:developer, applications, sync, */*, allow
        p, role:developer, applications, action/*, */*, allow
        p, role:developer, logs, get, */*, allow
        p, role:developer, exec, create, */*, deny
        p, role:developer, repositories, get, *, allow
        p, role:developer, clusters, get, *, allow
        p, role:developer, certificates, get, *, allow
        p, role:developer, projects, get, *, allow
        p, role:developer, accounts, *, *, deny
        p, role:developer, gpgkeys, *, *, deny
        p, role:developer, extensions, invoke, */*, deny
        g, Garmeres:admins, role:admin
        g, Garmeres:developers, role:developer
        g, Garmeres board, role:developer

    params:
      server.insecure: true
      server.x.frame.options: "SAMEORIGIN"
      server.content.security.policy: "frame-ancestors 'self' https://balve.garmeres.com"
