apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  encryptedData:
    redis-password: AgC4ak2nWNTPVRM74hzL62Au3cdYMpBr4r8xX6cJJN2UGpIvF6tGNSOHcl9J/ZCBe4lleHHhTBNhIDEP8PfnjU6vFTEOPfOhBohzC3WHrFkFbv5wA2uYGdSusZiWg5NckY+PNPLytNiSTygIhrjotqxlMWDd7Vqy38ptT9o/QygycndrJKqiYkykPOeOgBKcNbEJIG0/Lk9cE1kNIr4A0q4aQxviOm/PZ/4aU/Niu12i7NtJejFg/arBHcy7sJfqQOhAa1yQu/XSx3n+w4j5ZIYbZAv0jxafb092NVMnQINXdDANAhvWOi4Od46bcN24Ui6LOy8ihG+UITP8h0MTRrWpGe6X1OXOL5PEOw/gyqHFnvNqJRGHAkyn8XH/lBI518QJfBn8eBlcxC8pfQNABpfAQVKWsfMy+u0C1tWeF86IrEvkywQ3ptVZzxuXzINIp7h1XIR7E7tBckeDtWg0H5VtsYeiyngTRXbssUBY+DYZQDGK5npQTlPXrpYkkBQWEC1IEHC03hh9YdRDIKkr52yT4lwn/kiMKUuhVbHnuZCguSKb3dLs5cyCca7Y3hP1ZJ08ljg5K+7ACl2KayPsBxA6WECgBUS5a4zPgmHWo0z6aNVpRxbgkGb6zC5nk+Vs5DhfmJkmodV8b8yX7ONECVdXoOBKRsZWNLBd27my1GJHf1VoN+nevCTq7PcV80EVnUNhz5DHtQb7X4cbBNver9337vGjNg7IS2EYs5RHcA1305CtBDKrd1mwlFW2zRupe5s=
  template:
    metadata:
      name: nextcloud-redis
      namespace: nextcloud
