---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  encryptedData:
    mariadb-password: AgA7ifR5qa+7kssbsaXcUksTIH502y1BjcPp87vwBGx6xOLbAHllGS0y5LaUoaNIOjjHwrh+QkslBN6bRqPIFIimxbuM7kSo4CzCWAmCu3YMt5vy6JBnwGdYEtYhnC/vVa9fhlp4RFyCaUa/eFKB2qLBICqhPKgcSjwBYb+7RA8lyiVkYC74nVWZti6fjpsKk2lLfTQjui03gmRskY4OLVUxAVhp588mXU3rEGpVYnaIW1GZGKb0I/TijTx2MbukTwKKyL87maica1h0T6vm14/OMmnyU470TeCupiOc+ODHiDmmUytXUoxwbS/Zn1GpjmwbMlEymlfOI0H/MIi1wHNEMVDrjZ0g9IP6y3I7XqQt8eGb5mZH1gk+EWBtiS7/v9drtjmYysCiTfJ3mUzeFZZUntflsNJaAnCLADpQ5unycgjrz0z0Q4BJzpLbcO7q0EX92ykqnBVT8vi5qHk8QF4TAo99eSk0ZSfNMLhEZzSN3LRUmvqkPt1CA1oTGyxBUVs0n8nSwLn3AETpLow2n2bAMjehOOclr4dxNzhoNcSL1nFBQyE9Mha9PNjkxtjxqQKGeEjoTDh2tpbQALFAzJgM8CIgcSK4NEAIPU26uObBOho4bGKbVV9Zr/DBzB6qSfNphAtWgjiPqzdFc5XRDf/AvtJRwtfJZak6Lvzxfq9s4ViIJxgxRfuQBJiV0g0ZmXB8/uO8jA1zYe/i7J55dzDHdYAyzfkBrt0=
    mariadb-root-password: AgC8/in0eByvHxAkUQUKcgQ1lz4QWVuZVfAHgi/E0jDGelBDyNZffY8WabAY5KZ4QZlW4doGxiUSAwviQ6W5RhXy1Pm8wkVyu+ZBC8hN+yx9lhtp/4GLLSOQd/IVYdEalIMLrGDNZCHYU/nwazlZtLa1ZE+k8L6yAShbTVvsJ1BVaWVJUl4LQKqQR7r98pIg8mp+63iOAZjUym+ACZBs/m0t+gUqOjHp9wjL0f/PExchlTO2GkaLwd8/VEhbUCM98sKsq+yiNc2jEkauAYgJ7qBrFEYl7fZ52lOtKEv/TDjFAvhQaV5vKFY1sVnoh3V+sdl7S9NoRamp4F+BhsKxihTs97jnglhwGY9XKNTU+tZhogCJ/qGQhHGkxl0fWdDnAqXldlJ5wboNK93/wrFpTBz4/VZOWsTCf+/xv4CTbxVD9aV92/e0nlG6rTea2Egr1cvu1zeY0z9mIYAqGmEsRZ4eJDPBzaFbr8f5KmeWY/boEQNpNU2IWKHOy1s3fG+R2Emwcop8f/4VtnoEwcJiKNzv+rSSKbS5zj5F5VzKQcFCX/vpVD9wQxIKI7I9MWe/sNkZXOml72CnkSLGSq4PR8owaJN3SALrKo/JezR2BPs/wlbF1GdYLCLLEumgk4aX04F6TM7UBRutuyXPO2NYSQCosGEiJGRM+4rO2ogi6VgxJdHCph5uo9O+OBkK5YxkoWKBUMmf0pO8QhsF7QNeNO/BVgswErROOlE=
  template:
    metadata:
      name: nextcloud-mariadb
      namespace: nextcloud
