---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-s3
  namespace: nextcloud
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgARncjjRc/VOs/OjTCWDAh8hP/KqflyiEbZmCZnNmU/36PcK2Tk2c27ToIJNBo7YfIDdMoYKQVrq5JGNX6kwOzRXQHV+rw1hI3zwhVit93aZdYe8xOAcqGTD8jitAKx1vx4lwlvaK8Rw9V84kgQLg/s9wdn81kNR/v3zmobdLXvKgLbspnGGgy0963k7TyNBds1oZaRXunl6jaUxJDzwSBEJ0nMWHbJCOvX1Syr35u4Jq4fpp90C64cgUhpBhFkM0ipbVXYsybbeDiESKgBPfeMI5eb8jUSPzJQgoX/yQB6G8rQw8Ggg1R27d97PCAomWwY0Rv5QErMyLF7y42NrYpQB2VwOsjd5CLxltVrYg/BDriNOKTkkdZTtfH5nKiaaKvSMq8xx2iaN9eejl1VI8vCWUEHOlBZPhhfm434OXfL5lSerWvMxU1ufcFIrPnR34YWF88ehnZ6c/CORDX+QyNX8SVHLpTNnjUf3VfZFoD0tFktwAmd8GFZUdhX2UrQfc4O9HUkcA4cxaY5W2OBRpZ1DYSG780lXfDMtKfis4oNw+WC0frp3Z4AwSsYKIGxyv/aODZ9bGEPuCurdZUIxt5yEKgJ5CUKbg2dChJgl41ocGaCHhT4YDCM/sJKuUfdFttxfl0GxRuNZi0Ql0M+hyCOYhzs7o+gfZVz7x6Jl0LVYWu3xxDn6FW8RHuiDhJ6ov5r04qdERpKbCX13sGDn2Tk/EpW9A==
    S3_SECRET_ACCESS_KEY: AgBLhMBXW8AMZqyaofRqUO8KI+hXfrQQlSCtLGfSRTi1QR1TiWMPNbkbbgRqbnH5t8rXmOpg/8SodhMXYFwvn3UMa6cob/FbatCS0VXeYp4lER8SNJWcSaFtb1DTOp+AK4X9xVwz5gd6tsm4y1flzXwGychXG54RufWwtOtCJyjxLydsAI0d1mapsDLrlH6xPf6uejEH7CHoq9UqQhAdR2502sLq8cR0K6GDyHJvxQqyOpCqnNc+7OefpPfR3QfkVHw8trxLs0Kwy0eRLmyjgQxDANrt/LmytZg+8UDs2cCjKH9T+CeJLCEJtXsG8x3Znxa/QW1/rhUO/LAQp9wMyeIrmpNmuWidwfOsm20m7D1VvEcH9SRicVchcGzjrnZJQsurXIXrPmKSlTalsHtHIxNqTct495IPCpYx07OCgrTAzUod3UvQoNbs8Arc5HgCgEavNGXxZheCTeNYz0C+4nfAVojhi0WsEKFfW09odqPhJmKqy8A66aAbQvTmypavB0i25nvwpGKzKExSIQiGzt6FkxKiYOs0L/XLafZsmXP80716IoW/v1Kb1c01km3xifaEFh9ErSlr9S4sbgTlNvkYzcqcAa1PHntRL47n0B0+7IPnhRInwabHlXkWRiZACQvLesa7SifeWgDYSl50ZGJ12lhhJajGsO5Sb8Hb8BwNb8nnI9yvNFzWgNz8RXRPF/kzWpy/2soZndXL7en2RWBOnMFFZXzR8Q/Jr5Knc7nbgnHo6ogGPEAH
  template:
    metadata:
      name: nextcloud-s3
      namespace: nextcloud
