---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  encryptedData:
    redis-password: AgComKkJFxZnG527T8OpVQ9tEb3HAxwnuYEdX/Z2rSqb9MTVOW1erlG334AGia8GzBTW5DANOeP9Pzz+p1rWQ2TnPQAOEKhmKz1IjGC8SU0RqRH0BOSZCpk3uGaPqZXU+U3ACbfVEsRpAheguhTVozndH0Lcg9t8lT5LSbGkgRjue9bcDEo89MuvW51nmzfv6vTU+NctsizuLsvVKNHFq27R2SavHdg/FLNlBJ6KRe4zpdJTHJ31FztcA82FxoIGslA2ws6LxMMcHpV8gxRWH2NJW2bdIOp/QbfSPa/wCFX5SFFOO47x0I2R0yx/i2b6qSCESEC7LDwnQk0vxcm81RaTNPvUnsGDXdb8S3k4mhD/BrmZRJ6UmEW4dazT/3TEKFmkHgDT+icabvc1dgQEs6K6q7dZRswzXc09f39rKxLu+FrAhaa9vgnBiRfuIE0ICt0t0Z6MzNUmDzNRsBcjXYr3tJsV116Tyi5jZP6H4VUX9spGnZ14PJZNz9yCDOLkJhpiMbdhCmZpb2cn/aRz43rP+DkN1TJXVYco5dskfFjoMuZiJ9kmKx0vWdhyW5P8Es9PwxcaCbbryddQUkQ8HuSmKGAjAmxWaecuLewYj0daip4HtRo+RP5kxAZLRqA66kFaFNRSP6jvaL5O+IY7+mzzI0uDpXVeOQd727OeO8NAUnU7lhsqm3blIcwp/uODykzdC+dlJuYQ6ZYQ8Rt3ifwyfeBqUPg1W38p2hT1aUAVBQ==
  template:
    metadata:
      name: nextcloud-redis
      namespace: nextcloud
