---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-s3
  namespace: nextcloud
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgC1qO3AHyQFFn2hWRMNue+dJFPShjbQVoiVbAwadTOz5KJWTH3uyu9M1184zmrv92YQWTo6oKGhG68oIyUFc2p4cyhFgrq3H9AJDIj0UOkqmbwiQq/OFWE3W8uF3qzjCTrWlpRRf3+w0NufaSgDDq7Tw0Na9lxd8MplxZ1c8AT1a/IqBQISsDnyZR/9As8zi16+XCtGxNAYgrCduhLi4Ut3Pk0+dZ+sN2qbvzjG6p0S2fm+Ch4QQm+leWfEe8e/NckjeV3NIGwjx1VDqW+eDCWyz2x7SJ6/A1A9I2CGmDsb3KGvcnMbsrIyEH1ssfQ0/YsujboHYag1cFV+RLrh32wwfevrdmHE6xLcv+YGPMgi9aE1JU3D/LaV5uJEfK8nhYTZom6cbK0EmQO1yWnIKUsI2TjFRLfqP6kL4XhpD6ca980lOdmaUXdb1GfF47zh4u23hgiTsAg8Z7lk4MKAsF6JeUu4p9Xnj9Zg+VbcngjzGuPgN+I1//fIUnExqlFEUndr775gI/TGoN7GtnpaFeud3te4PYpncnQahBReLsS6aI6p9ztujV1+ajrrDJ/S1KgfZ/cIOc7COn4m6L6nDzIxmnV25jh1HNz2SH0XzdNy7DSEWyyJA7qb7N48W9dLVqoo1HgKWCDJGSRcPUfGsqxVhxr8Svr3V/oQa60QnoYflAxbLzHPSiH37WkQMW4pNOunkLyrHxMD2Dbi3md9B2L9iLNPjA==
    S3_SECRET_ACCESS_KEY: AgBLOICMN1yEgtPrsRr8wxvqwpLc/fs254RPsH2Pul1j2UcPIcP5txB543wz+Icys4jLMApHWH82YZQwzjZz0/1ry8ajoTowO6/Qg5xnm/0N8SDFBV6cCI0uHhBrDWe0l68/Z5XfZP5Du8Q5enDV/h6IJQ9rS4nPsvW256jGmSaNBUGkRlSu2VqBxMFmVUD9IyhxGNxP2DeqVbGaSlucPSMOtXmUqnIUfk3ETVknUznD1YCZ1zKuwGGl1DN8hSgT0+/shlAoFIImHjweyKBsiY40pcdZvUTxI3AUONSosHI/ulnVBZL9+U0A+Vj5rN23pgM6KNFGvvBUiPQfRHITq2hrCLnEPYVDsDQkQ2v5B5X+YsGwvrmFiHNF7+7TIBau4d1R7ALj/gtb7bYFivzHoDN+Ulvn2HoQOSZxzbkwFV/dysxrSCSnCazxoGFS6cc9TSNgjo2i1JCge0pgqquM+noFM207kuvhINbZZ88BHNA2Jcji+ZGqr8L6IBR9sVdOamwI8j5K+ZjxGnh/h/rVmpHRSjeWIgw0/T6/mqIRXnUAZEmMuWsfWoiCvcTSHAmWUO1J02gNY/lxXpVv09MwjjGxhhIHKJ8OzL8ZI6/R8lmsT+NzKh0DHTTe0IEuF2YVRzSXpKLew0vEfkl97scFSo++kOg9ItFekbzNDUw4bXsw5dk1kQWVz6Vw1ZcoQE2cVXA5s1lxI1li0Ys4SmFelcimiEtKwd8L0U+F3r0PhKf/xdBpo2/l/KgE
  template:
    metadata:
      name: nextcloud-s3
      namespace: nextcloud
